seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false
  - page_type: categories
    file: ./parsers/categories.rb
    disabled: false
  - page_type: reviews
    file: ./parsers/reviews.rb
exporters:
  - file: ./exporters/categories_list_json.yaml
    disabled: false
  - file: ./exporters/sub_cat_json.yaml
    disabled: false
  - file: ./exporters/reviews_json.yaml
    disabled: false